version: '3.8'

services:
  alpaca-trader:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alpaca-trader
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - ./models:/app/models
    environment:
      - ALPACA_API_KEY=${ALPACA_API_KEY}
      - ALPACA_API_SECRET=${ALPACA_API_SECRET}
      - ALPACA_BASE_URL=${ALPACA_BASE_URL:-https://paper-api.alpaca.markets}
      - ALPACA_DATA_URL=${ALPACA_DATA_URL:-https://data.alpaca.markets}
      - TZ=America/New_York
    env_file:
      - .env